DROP TABLE IF EXISTS insumos;

CREATE TABLE insumos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nome_insumo TEXT NOT NULL,
    beneficios TEXT NOT NULL
);